# Change these first
owner: tizoy12 # Your GitHub organization or username, where this repository lives
repo: GanzPinger # The name of this repository

sites:
  - name: DragonNest SEA Status
    check: "tcp-ping"
    url: 52.230.66.176
    port: 14503

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /GanzPinger # "repo" is your repository name
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: https://tizoy12.github.io/GanzPinger/
    - title: GitHub
      href: https://github.com/tizoy12/GanzPinger

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
