# Change these first
owner: LeinadKenbun # Your GitHub organization or username, where this repository lives
repo: GanzPinger # The name of this repository

sites:
  #- #name: AniSchedule 
    #url: https://AniSchedule.ganzbot.repl.co
  #- name: GanzBot
    #url: https://ganzbot.repl.co/
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /GanzPinger # "repo" is your repository name
  # baseUrl: /your-repo-name
  favicon: https://media.discordapp.net/attachments/595551516442624019/848915878812450856/elves.png
  logoUrl: https://media.discordapp.net/attachments/595551516442624019/848915878812450856/elves.png
  name: GanzPinger
  navbar:
    - title: Dashboard
      href: https://LeinadKenbun.github.io/GanzPinger/
    - title: GitHub
      href: https://github.com/LeinadKenbun/GanzPinger

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
